### ISSUE TITLE
Install from requirements files in submodules

### ISSUE THREAD

**Issue by mattdodge** [neutralio/nio-cli#12]
Right now, we recursively look for requirements.txt files when you run `nio add -U`. However, we don't do that when you add a single block. 

Do we want to dive into submodules and folders when adding a block and look for `requirements.txt` files? This could be useful for something like the `oauth2_mixin` but it could be bad with something like the `mixins` submodule, where you may not use all of the mixins in the submodule

**Comment by hansmosh** [comment]
At first I didn't like the idea of doing a recursive install but it's growing on me. We could always consider splitting up the mixins into separate repos: group_by_mixin, etc...

**Comment by mattdodge** [comment]
Yeah, I actually think we should split the mixins up regardless. I'm cool
with recursive install too though
